apiVersion: v1
kind: Service  # リソースの種類をServiceに
metadata:
  name: nginx-svc   # Service名、名前解決に利用
spec:
  type: ClusterIP
  selector:    # ServiceのターゲットとするPodのラベル
    app: nginx
  ports:
    - name: http
      port: 80 # 転送先port

      