apiVersion: v1
kind: Service  # リソースの種類をServiceに
metadata:
  name: nginx   # Service名、名前解決に利用
spec:
  selector:    # ServiceのターゲットとするPodのラベル
    app: nginx
    release: osaka
  ports:
    - name: http
      port: 80 # 転送先port
