apiVersion: apps/v1
kind: ReplicaSet  # ReplicaSetのマニフェスト
metadata:         # ReplicaSetのメタデータ
  name: simple-rs 
  labels:
    app: simple 
spec:
  replicas: 2     # Podの複製数 
  selector:
    matchLabels:  # ReplicaSetが管理(検索)するPodのラベル
      app: simple 
  template:       # template以下はPodリソースにおけるspec定義と同じ
    metadata:
      labels:     # Podのlabelを定義
        app: simple
    spec:         #コンテナの定義(simple-pod.yamlの定義と同じ)
      containers:
      - name: nginx 
        image: nginx:1.13 
        env: 
        - name: BACKEND_HOST
          value: localhost:8080
        ports:
        - containerPort: 80 
      - name: alpine
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do date; sleep 10;done"]
