apiVersion: v1
kind: Pod           # リソースの種類を指定する。kindの値でspec配下スキーマが変化
metadata:
  name: simple-pod  # リソースの名称として利用される
  labels:           # Podのlabelを定義
    app: simple
spec:               # kindがPodのため、Podを構成するコンテナ群をcontainersに定義
  containers:
  - name: nginx     # コンテナの名前
    image: nginx:1.13   # コンテナイメージの指定
    env:            # コンテナで利用される環境変数
    - name: BACKEND_HOST
      value: localhost:8080
    ports:          # EXPOSEするポートの指定
    - containerPort: 80 
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep 10;done"]