apiVersion: v1
kind: Service           # Serviceのマニフェスト
metadata:
  name: redis-slave     # Service名
  labels:               # Serviceにつけるラベル
    app: redis
    role: slave
    tier: backend
spec:
  ports:                # targetPortが省略されている場合はportと同じ値となる
  - port: 6379          # Serviceの受け付けるポート
  selector:             # ServiceのターゲットとするPodのラベル
    app: redis
    role: slave
    tier: backend
