apiVersion: v1
kind: Namespace       # ログ監視用のNamespaceを作成
metadata:
  name: monitoring
---
apiVersion: v1
kind: Secret          # InfluxDBの接続情報
metadata:
  name: influxdb-secret
  namespace: monitoring
type: Opaque          # スキーマレスでsecret を定義するタイプ
data:                 # 渡したい値を Key: Value の形式で定義
  INFLUXDB_DATABASE: bG9jYWxfbW9uaXRvcmluZw==  # 「local_monitoring」
  INFLUXDB_USERNAME: c2FtcGxl                  # 「sample」のbase64エンコード
  INFLUXDB_PASSWORD: cGFzc3dvcmQ=              # 「password」のbase64エンコード
---
apiVersion: apps/v1
kind: StatefulSet     # InfluxDB Pod 用StatefulSet(PVを持つPod)
metadata:
  namespace: monitoring
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1         # Master1台構成
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: influxdb-secret
        image: docker.io/influxdb:1.6.4
        name: influxdb
        volumeMounts:                   # PVをマウント
        - mountPath: /var/lib/influxdb
          name: var-lib-influxdb
  volumeClaimTemplates:                 # PVC
  - metadata:
      name: var-lib-influxdb
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
spec:
  clusterIP: None
  selector:
    app: influxdb
